/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as N4RouteImport } from './routes/n4'
import { Route as RefRouteImport } from './routes/ref'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StartRouteImport } from './routes/start'
import { Route as ExamIndexRouteImport } from './routes/exam.index'
import { Route as ExamIdRouteImport } from './routes/exam.$id'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as UnitIdRouteImport } from './routes/unit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const N4Route = N4RouteImport.update({
  id: '/n4',
  path: '/n4',
  getParentRoute: () => rootRouteImport,
} as any)
const RefRoute = RefRouteImport.update({
  id: '/ref',
  path: '/ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamRoute,
} as any)
const ExamIdRoute = ExamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExamRoute,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitIdRoute = UnitIdRouteImport.update({
  id: '/unit/$id',
  path: '/unit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam': typeof ExamRouteWithChildren
  '/n4': typeof N4Route
  '/ref': typeof RefRoute
  '/review': typeof ReviewRoute
  '/start': typeof StartRoute
  '/exam/$id': typeof ExamIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/unit/$id': typeof UnitIdRoute
  '/exam/': typeof ExamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/n4': typeof N4Route
  '/ref': typeof RefRoute
  '/review': typeof ReviewRoute
  '/start': typeof StartRoute
  '/exam/$id': typeof ExamIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/unit/$id': typeof UnitIdRoute
  '/exam': typeof ExamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam': typeof ExamRouteWithChildren
  '/n4': typeof N4Route
  '/ref': typeof RefRoute
  '/review': typeof ReviewRoute
  '/start': typeof StartRoute
  '/exam/$id': typeof ExamIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/unit/$id': typeof UnitIdRoute
  '/exam/': typeof ExamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam'
    | '/n4'
    | '/ref'
    | '/review'
    | '/start'
    | '/exam/$id'
    | '/lesson/$id'
    | '/unit/$id'
    | '/exam/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/n4'
    | '/ref'
    | '/review'
    | '/start'
    | '/exam/$id'
    | '/lesson/$id'
    | '/unit/$id'
    | '/exam'
  id:
    | '__root__'
    | '/'
    | '/exam'
    | '/n4'
    | '/ref'
    | '/review'
    | '/start'
    | '/exam/$id'
    | '/lesson/$id'
    | '/unit/$id'
    | '/exam/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRoute: typeof ExamRouteWithChildren
  N4Route: typeof N4Route
  RefRoute: typeof RefRoute
  ReviewRoute: typeof ReviewRoute
  StartRoute: typeof StartRoute
  LessonIdRoute: typeof LessonIdRoute
  UnitIdRoute: typeof UnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n4': {
      id: '/n4'
      path: '/n4'
      fullPath: '/n4'
      preLoaderRoute: typeof N4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref': {
      id: '/ref'
      path: '/ref'
      fullPath: '/ref'
      preLoaderRoute: typeof RefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/$id': {
      id: '/exam/$id'
      path: '/$id'
      fullPath: '/exam/$id'
      preLoaderRoute: typeof ExamIdRouteImport
      parentRoute: typeof ExamRoute
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$id': {
      id: '/unit/$id'
      path: '/unit/$id'
      fullPath: '/unit/$id'
      preLoaderRoute: typeof UnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExamRouteChildren {
  ExamIdRoute: typeof ExamIdRoute
  ExamIndexRoute: typeof ExamIndexRoute
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamIdRoute: ExamIdRoute,
  ExamIndexRoute: ExamIndexRoute,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRoute: ExamRouteWithChildren,
  N4Route: N4Route,
  RefRoute: RefRoute,
  ReviewRoute: ReviewRoute,
  StartRoute: StartRoute,
  LessonIdRoute: LessonIdRoute,
  UnitIdRoute: UnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
